apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
        app: frontendwebapp
    spec:
      containers: 
        - image: naynnpn/wwa-frontend-image::v1.0
          imagePullPolicy: Always
          name: myweb
          ports: 
            - containerPort: 3000
          env:
            - name: "wwadb"
              value: db-service
            - name: MONGO_ROOT_USER
              value: "shreyashettys202"
            - name: MONGO_ROOT_PASSWORD
              value: "dg3KtsSYXuSc0t5f"
          resources:
            limits:
              memory: 500Mi
              cpu: 100m
            requests:
              memory: 250Mi
              cpu: 80m
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
  labels:
    name: web
    app: frontendwebapp
spec:
  selector:
    name: web
  type: NodePort
  ports:
   - name: http
     port: 3000
     targetPort: 3000
     nodePort: 30001
     protocol: TCP
